spring:
  profiles:
    active: dev
  application:
     name: bc-provider-company-employee
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql