server:
  port: 8004
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: nBjttsF_001!root
    url: jdbc:mysql://192.168.9.151:3306/ttsf?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 192.168.9.151
    port: 6379
    password: redisroot
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.9.151:8761/eureka/