spring:
  profiles:
    active: dev
  application:
    name: bc-provider-user-role
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql