spring:
  profiles:
    active: dev
  application:
    name: bc-provider-project-model
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql